<?php
namespace Orchid\Controller;

use Zend\Mvc\Controller\AbstractActionController,
    Zend\View\Model\ViewModel;

class CountryController extends AbstractActionController
{
    public function findAction()
    {
		$countries = array(
			array('name' => 'Afghanistan', 'currency' => 'Afghani', 'currency_code' => 'AFN'),
			array('name' => 'Åland Islands', 'currency' => 'Euro', 'currency_code' => 'EUR'),
			array('name' => 'Albania', 'currency' => 'Lek', 'currency_code' => 'ALL'),
			array('name' => 'Algeria', 'currency' => 'Algerian Dinar', 'currency_code' => 'DZD'),
			array('name' => 'American Samoa', 'currency' => 'US Dollar', 'currency_code' => 'USD'),
			array('name' => 'Andorra', 'currency' => 'Euro', 'currency_code' => 'EUR'),
			array('name' => 'Angola', 'currency' => 'Kwanza', 'currency_code' => 'AOA'),
			array('name' => 'Anguilla', 'currency' => 'East Caribbean Dollar', 'currency_code' => 'XCD'),
			array('name' => 'Antarctica', 'currency' => 'No universal currency', 'currency_code' => ''),
			array('name' => 'Antigua and Barbuda', 'currency' => 'East Caribbean Dollar', 'currency_code' => 'XCD'),
			array('name' => 'Argentina', 'currency' => 'Argentine Peso', 'currency_code' => 'ARS'),
			array('name' => 'Armenia', 'currency' => 'Armenian Dram', 'currency_code' => 'AMD'),
			array('name' => 'Aruba', 'currency' => 'Aruban Florin', 'currency_code' => 'AWG'),
			array('name' => 'Australia', 'currency' => 'Australian Dollar', 'currency_code' => 'AUD'),
			array('name' => 'Austria', 'currency' => 'Euro', 'currency_code' => 'EUR'),
			array('name' => 'Azerbaijan', 'currency' => 'Azerbaijanian Manat', 'currency_code' => 'AZN'),
			array('name' => 'Bahamas', 'currency' => 'Bahamian Dollar', 'currency_code' => 'BSD'),
			array('name' => 'Bahrain', 'currency' => 'Bahraini Dinar', 'currency_code' => 'BHD'),
			array('name' => 'Bangladesh', 'currency' => 'Taka', 'currency_code' => 'BDT'),
			array('name' => 'Barbados', 'currency' => 'Barbados Dollar', 'currency_code' => 'BBD'),
			array('name' => 'Belarus', 'currency' => 'Belarussian Ruble', 'currency_code' => 'BYR'),
			array('name' => 'Belgium', 'currency' => 'Euro', 'currency_code' => 'EUR'),
			array('name' => 'Belize', 'currency' => 'Belize Dollar', 'currency_code' => 'BZD'),
			array('name' => 'Benin', 'currency' => 'CFA Franc BCEAO †', 'currency_code' => 'XOF'),
			array('name' => 'Bermuda', 'currency' => 'Bermudian Dollar', 'currency_code' => 'BMD'),
			array('name' => 'Bhutan', 'currency' => 'Ngultrum', 'currency_code' => 'BTN'),
			array('name' => 'Bolivia, Plurinational State of', 'currency' => 'Boliviano', 'currency_code' => 'BOB'),
			array('name' => 'Bonaire, Sint Eustatius and Saba', 'currency' => 'US Dollar', 'currency_code' => 'USD'),
			array('name' => 'Bosnia and Herzegovina', 'currency' => 'Convertible Marks', 'currency_code' => 'BAM'),
			array('name' => 'Botswana', 'currency' => 'Pula', 'currency_code' => 'BWP'),
			array('name' => 'Bouvet Island', 'currency' => 'Norwegian Krone', 'currency_code' => 'NOK'),
			array('name' => 'Brazil', 'currency' => 'Brazilian Real', 'currency_code' => 'BRL'),
			array('name' => 'British Indian Ocean Territory', 'currency' => 'US Dollar', 'currency_code' => 'USD'),
			array('name' => 'Brunei Darussalam', 'currency' => 'Brunei Dollar', 'currency_code' => 'BND'),
			array('name' => 'Bulgaria', 'currency' => 'Bulgarian Lev', 'currency_code' => 'BGN'),
			array('name' => 'Burkina Faso', 'currency' => 'CFA Franc BCEAO †', 'currency_code' => 'XOF'),
			array('name' => 'Burundi', 'currency' => 'Burundi Franc', 'currency_code' => 'BIF'),
			array('name' => 'Cambodia', 'currency' => 'Riel', 'currency_code' => 'KHR'),
			array('name' => 'Cameroon', 'currency' => 'CFA Franc BEAC ‡', 'currency_code' => 'XAF'),
			array('name' => 'Canada', 'currency' => 'Canadian Dollar', 'currency_code' => 'CAD'),
			array('name' => 'Cape Verde', 'currency' => 'Cape Verde Escudo', 'currency_code' => 'CVE'),
			array('name' => 'Cayman Islands', 'currency' => 'Cayman Islands Dollar', 'currency_code' => 'KYD'),
			array('name' => 'Central African Republic', 'currency' => 'CFA Franc BEAC ‡', 'currency_code' => 'XAF'),
			array('name' => 'Chad', 'currency' => 'CFA Franc BEAC ‡', 'currency_code' => 'XAF'),
			array('name' => 'Chile', 'currency' => 'Chilean Peso', 'currency_code' => 'CLP'),
			array('name' => 'China', 'currency' => 'Yuan Renminbi', 'currency_code' => 'CNY'),
			array('name' => 'Christmas Island', 'currency' => 'Australian Dollar', 'currency_code' => 'AUD'),
			array('name' => 'Cocos (Keeling) Islands', 'currency' => 'Australian Dollar', 'currency_code' => 'AUD'),
			array('name' => 'Colombia', 'currency' => 'Colombian Peso', 'currency_code' => 'COP'),
			array('name' => 'Comoros', 'currency' => 'Comoro Franc', 'currency_code' => 'KMF'),
			array('name' => 'Congo', 'currency' => 'CFA Franc BEAC ‡', 'currency_code' => 'XAF'),
			array('name' => 'Congo, The Democratic Republic of the', 'currency' => 'Franc Congolais', 'currency_code' => 'CDF'),
			array('name' => 'Cook Islands', 'currency' => 'New Zealand Dollar', 'currency_code' => 'NZD'),
			array('name' => 'Costa Rica', 'currency' => 'Costa Rican Colon', 'currency_code' => 'CRC'),
			array('name' => 'Côte D\'Ivoire', 'currency' => 'CFA Franc BCEAO †', 'currency_code' => 'XOF'),
			array('name' => 'Croatia', 'currency' => 'Croatian Kuna', 'currency_code' => 'HRK'),
			array('name' => 'Cuba', 'currency' => 'Cuban Peso', 'currency_code' => 'CUP'),
			array('name' => 'Curaço', 'currency' => 'Netherlands Antillean Guilder', 'currency_code' => 'ANG'),
			array('name' => 'Cyprus', 'currency' => 'Cyprus Pound', 'currency_code' => 'CYP'),
			array('name' => 'Czech Republic', 'currency' => 'Czech Koruna', 'currency_code' => 'CZK'),
			array('name' => 'Denmark', 'currency' => 'Danish Krone', 'currency_code' => 'DKK'),
			array('name' => 'Djibouti', 'currency' => 'Djibouti Franc', 'currency_code' => 'DJF'),
			array('name' => 'Dominica', 'currency' => 'East Caribbean Dollar', 'currency_code' => 'XCD'),
			array('name' => 'Dominican Republic', 'currency' => 'Dominican Peso', 'currency_code' => 'DOP'),
			array('name' => 'Ecuador', 'currency' => 'US Dollar', 'currency_code' => 'USD'),
			array('name' => 'Egypt', 'currency' => 'Egyptian Pound', 'currency_code' => 'EGP'),
			array('name' => 'El Salvador', 'currency' => 'El Salvador Colon', 'currency_code' => 'SVC'),
			array('name' => 'Equatorial Guinea', 'currency' => 'CFA Franc BEAC ‡', 'currency_code' => 'XAF'),
			array('name' => 'Eritrea', 'currency' => 'Nakfa', 'currency_code' => 'ERN'),
			array('name' => 'Estonia', 'currency' => 'Euro', 'currency_code' => 'EUR'),
			array('name' => 'Ethiopia', 'currency' => 'Ethiopian Birr', 'currency_code' => 'ETB'),
			array('name' => 'European Economic and Monetary Union area', 'currency' => 'Euro', 'currency_code' => 'EUR'),
			array('name' => 'Falkland Islands (Malvinas)', 'currency' => 'Falkland Islands Pound', 'currency_code' => 'FKP'),
			array('name' => 'Faroe Islands', 'currency' => 'Danish Krone', 'currency_code' => 'DKK'),
			array('name' => 'Fiji', 'currency' => 'Fiji Dollar', 'currency_code' => 'FJD'),
			array('name' => 'Finland', 'currency' => 'Euro', 'currency_code' => 'EUR'),
			array('name' => 'France', 'currency' => 'Euro', 'currency_code' => 'EUR'),
			array('name' => 'French Guiana', 'currency' => 'Euro', 'currency_code' => 'EUR'),
			array('name' => 'French Polynesia', 'currency' => 'CFP Franc', 'currency_code' => 'XPF'),
			array('name' => 'French Southern Territories', 'currency' => 'Euro', 'currency_code' => 'EUR'),
			array('name' => 'Gabon', 'currency' => 'CFA Franc BEAC ‡', 'currency_code' => 'XAF'),
			array('name' => 'Gambia', 'currency' => 'Dalasi', 'currency_code' => 'GMD'),
			array('name' => 'Georgia', 'currency' => 'Lari', 'currency_code' => 'GEL'),
			array('name' => 'Germany', 'currency' => 'Euro', 'currency_code' => 'EUR'),
			array('name' => 'Ghana', 'currency' => 'Ghana Cedi', 'currency_code' => 'GHS'),
			array('name' => 'Gibraltar', 'currency' => 'Gibraltar Pound', 'currency_code' => 'GIP'),
			array('name' => 'Greece', 'currency' => 'Euro', 'currency_code' => 'EUR'),
			array('name' => 'Greenland', 'currency' => 'Danish Krone', 'currency_code' => 'DKK'),
			array('name' => 'Grenada', 'currency' => 'East Caribbean Dollar', 'currency_code' => 'XCD'),
			array('name' => 'Guadeloupe', 'currency' => 'Euro', 'currency_code' => 'EUR'),
			array('name' => 'Guam', 'currency' => 'US Dollar', 'currency_code' => 'USD'),
			array('name' => 'Guatemala', 'currency' => 'Quetzal', 'currency_code' => 'GTQ'),
			array('name' => 'Guernsey', 'currency' => 'Pound Sterling', 'currency_code' => 'GBP'),
			array('name' => 'Guinea', 'currency' => 'Guinea Franc', 'currency_code' => 'GNF'),
			array('name' => 'Guinea-Bissau', 'currency' => 'Guinea-Bissau Peso', 'currency_code' => 'GWP'),
			array('name' => 'Guyana', 'currency' => 'Guyana Dollar', 'currency_code' => 'GYD'),
			array('name' => 'Haiti', 'currency' => 'Gourde', 'currency_code' => 'HTG'),
			array('name' => 'Heard Island and McDonald Islands', 'currency' => 'Australian Dollar', 'currency_code' => 'AUD'),
			array('name' => 'Holy See (Vatican City State)', 'currency' => 'Euro', 'currency_code' => 'EUR'),
			array('name' => 'Honduras', 'currency' => 'Lempira', 'currency_code' => 'HNL'),
			array('name' => 'Hong Kong', 'currency' => 'Hong Kong Dollar', 'currency_code' => 'HKD'),
			array('name' => 'Hungary', 'currency' => 'Forint', 'currency_code' => 'HUF'),
			array('name' => 'Iceland', 'currency' => 'Iceland Krona', 'currency_code' => 'ISK'),
			array('name' => 'India', 'currency' => 'Indian Rupee', 'currency_code' => 'INR'),
			array('name' => 'Indonesia', 'currency' => 'Rupiah', 'currency_code' => 'IDR'),
			array('name' => 'Iran, Islamic Republic Of', 'currency' => 'Iranian Rial', 'currency_code' => 'IRR'),
			array('name' => 'Iraq', 'currency' => 'Iraqi Dinar', 'currency_code' => 'IQD'),
			array('name' => 'Ireland', 'currency' => 'Euro', 'currency_code' => 'EUR'),
			array('name' => 'Isle of Man', 'currency' => 'Pound Sterling', 'currency_code' => 'GBP'),
			array('name' => 'Israel', 'currency' => 'New Israeli Sheqel', 'currency_code' => 'ILS'),
			array('name' => 'Italy', 'currency' => 'Euro', 'currency_code' => 'EUR'),
			array('name' => 'Jamaica', 'currency' => 'Jamaican Dollar', 'currency_code' => 'JMD'),
			array('name' => 'Japan', 'currency' => 'Yen', 'currency_code' => 'JPY'),
			array('name' => 'Jersey', 'currency' => 'Pound Sterling', 'currency_code' => 'GBP'),
			array('name' => 'Jordan', 'currency' => 'Jordanian Dinar', 'currency_code' => 'JOD'),
			array('name' => 'Kazakhstan', 'currency' => 'Tenge', 'currency_code' => 'KZT'),
			array('name' => 'Kenya', 'currency' => 'Kenyan Shilling', 'currency_code' => 'KES'),
			array('name' => 'Kiribati', 'currency' => 'Australian Dollar', 'currency_code' => 'AUD'),
			array('name' => 'Korea, Democratic People\'s Republic of', 'currency' => 'North Korean Won', 'currency_code' => 'KPW'),
			array('name' => 'Korea, Republic of', 'currency' => 'Won', 'currency_code' => 'KRW'),
			array('name' => 'Kuwait', 'currency' => 'Kuwaiti Dinar', 'currency_code' => 'KWD'),
			array('name' => 'Kyrgyzstan', 'currency' => 'Som', 'currency_code' => 'KGS'),
			array('name' => 'Lao People\'s Democratic Republic', 'currency' => 'Kip', 'currency_code' => 'LAK'),
			array('name' => 'Latvia', 'currency' => 'Latvian Lats', 'currency_code' => 'LVL'),
			array('name' => 'Lebanon', 'currency' => 'Lebanese Pound', 'currency_code' => 'LBP'),
			array('name' => 'Lesotho', 'currency' => 'Loti', 'currency_code' => 'LSL'),
			array('name' => 'Liberia', 'currency' => 'Liberian Dollar', 'currency_code' => 'LRD'),
			array('name' => 'Libya', 'currency' => 'Libyan Dinar', 'currency_code' => 'LYD'),
			array('name' => 'Liechtenstein', 'currency' => 'Swiss Franc', 'currency_code' => 'CHF'),
			array('name' => 'Lithuania', 'currency' => 'Lithuanian Litas', 'currency_code' => 'LTL'),
			array('name' => 'Luxembourg', 'currency' => 'Euro', 'currency_code' => 'EUR'),
			array('name' => 'Macao', 'currency' => 'Pataca', 'currency_code' => 'MOP'),
			array('name' => 'Macedonia, The Former Yugoslav Republic of', 'currency' => 'Denar', 'currency_code' => 'MKD'),
			array('name' => 'Madagascar', 'currency' => 'Malagasy Ariary', 'currency_code' => 'MGA'),
			array('name' => 'Malawi', 'currency' => 'Kwacha', 'currency_code' => 'MWK'),
			array('name' => 'Malaysia', 'currency' => 'Malaysian Ringgit', 'currency_code' => 'MYR'),
			array('name' => 'Maldives', 'currency' => 'Rufiyaa', 'currency_code' => 'MVR'),
			array('name' => 'Mali', 'currency' => 'CFA Franc BCEAO †', 'currency_code' => 'XOF'),
			array('name' => 'Malta', 'currency' => 'Euro', 'currency_code' => 'EUR'),
			array('name' => 'Marshall Islands', 'currency' => 'US Dollar', 'currency_code' => 'USD'),
			array('name' => 'Martinique', 'currency' => 'Euro', 'currency_code' => 'EUR'),
			array('name' => 'Mauritania', 'currency' => 'Ouguiya', 'currency_code' => 'MRO'),
			array('name' => 'Mauritius', 'currency' => 'Mauritius Rupee', 'currency_code' => 'MUR'),
			array('name' => 'Mayotte', 'currency' => 'Euro', 'currency_code' => 'EUR'),
			array('name' => 'Mexico', 'currency' => 'Mexican Peso', 'currency_code' => 'MXN'),
			array('name' => 'Micronesia, Federated States of', 'currency' => 'US Dollar', 'currency_code' => 'USD'),
			array('name' => 'Moldova, Republic of', 'currency' => 'Moldovan Leu', 'currency_code' => 'MDL'),
			array('name' => 'Monaco', 'currency' => 'Euro', 'currency_code' => 'EUR'),
			array('name' => 'Mongolia', 'currency' => 'Tugrik', 'currency_code' => 'MNT'),
			array('name' => 'Montenegro', 'currency' => 'Euro', 'currency_code' => 'EUR'),
			array('name' => 'Montserrat', 'currency' => 'East Caribbean Dollar', 'currency_code' => 'XCD'),
			array('name' => 'Morocco', 'currency' => 'Moroccan Dirham', 'currency_code' => 'MAD'),
			array('name' => 'Mozambique', 'currency' => 'Mozambique Metical', 'currency_code' => 'MZN'),
			array('name' => 'Myanmar', 'currency' => 'Kyat', 'currency_code' => 'MMK'),
			array('name' => 'Namibia', 'currency' => 'Namibia Dollar', 'currency_code' => 'NAD'),
			array('name' => 'Nauru', 'currency' => 'Australian Dollar', 'currency_code' => 'AUD'),
			array('name' => 'Nepal', 'currency' => 'Nepalese Rupee', 'currency_code' => 'NPR'),
			array('name' => 'Netherlands', 'currency' => 'Euro', 'currency_code' => 'EUR'),
			array('name' => 'Netherlands Antilles', 'currency' => 'Netherlands Antillean Guilder', 'currency_code' => 'ANG'),
			array('name' => 'New Caledonia', 'currency' => 'CFP Franc', 'currency_code' => 'XPF'),
			array('name' => 'New Zealand', 'currency' => 'New Zealand Dollar', 'currency_code' => 'NZD'),
			array('name' => 'Nicaragua', 'currency' => 'Cordoba Oro', 'currency_code' => 'NIO'),
			array('name' => 'Niger', 'currency' => 'CFA Franc BCEAO †', 'currency_code' => 'XOF'),
			array('name' => 'Nigeria', 'currency' => 'Naira', 'currency_code' => 'NGN'),
			array('name' => 'Niue', 'currency' => 'New Zealand Dollar', 'currency_code' => 'NZD'),
			array('name' => 'Norfolk Island', 'currency' => 'Australian Dollar', 'currency_code' => 'AUD'),
			array('name' => 'Northern Mariana Islands', 'currency' => 'US Dollar', 'currency_code' => 'USD'),
			array('name' => 'Norway', 'currency' => 'Norwegian Krone', 'currency_code' => 'NOK'),
			array('name' => 'Oman', 'currency' => 'Rial Omani', 'currency_code' => 'OMR'),
			array('name' => 'Pakistan', 'currency' => 'Pakistan Rupee', 'currency_code' => 'PKR'),
			array('name' => 'Palau', 'currency' => 'US Dollar', 'currency_code' => 'USD'),
			array('name' => 'Palestinian Territory, Occupied', 'currency' => 'No universal currency', 'currency_code' => ''),
			array('name' => 'Panama', 'currency' => 'Balboa', 'currency_code' => 'PAB'),
			array('name' => 'Papua New Guinea', 'currency' => 'Kina', 'currency_code' => 'PGK'),
			array('name' => 'Paraguay', 'currency' => 'Guarani', 'currency_code' => 'PYG'),
			array('name' => 'Peru', 'currency' => 'Nuevo Sol', 'currency_code' => 'PEN'),
			array('name' => 'Philippines', 'currency' => 'Philippine Peso', 'currency_code' => 'PHP'),
			array('name' => 'Pitcairn', 'currency' => 'New Zealand Dollar', 'currency_code' => 'NZD'),
			array('name' => 'Poland', 'currency' => 'Zloty', 'currency_code' => 'PLN'),
			array('name' => 'Portugal', 'currency' => 'Euro', 'currency_code' => 'EUR'),
			array('name' => 'Puerto Rico', 'currency' => 'US Dollar', 'currency_code' => 'USD'),
			array('name' => 'Qatar', 'currency' => 'Qatari Rial', 'currency_code' => 'QAR'),
			array('name' => 'Réunion', 'currency' => 'Euro', 'currency_code' => 'EUR'),
			array('name' => 'Romania', 'currency' => 'New Romanian Leu', 'currency_code' => 'RON'),
			array('name' => 'Russian Federation', 'currency' => 'Russian Ruble', 'currency_code' => 'RUB'),
			array('name' => 'Rwanda', 'currency' => 'Rwanda Franc', 'currency_code' => 'RWF'),
			array('name' => 'Saint Barthélemy', 'currency' => 'Euro', 'currency_code' => 'EUR'),
			array('name' => 'Saint Helena, Ascension and Tristan Da Cunha', 'currency' => 'Saint Helena Pound', 'currency_code' => 'SHP'),
			array('name' => 'Saint Kitts and Nevis', 'currency' => 'East Caribbean Dollar', 'currency_code' => 'XCD'),
			array('name' => 'Saint Lucia', 'currency' => 'East Caribbean Dollar', 'currency_code' => 'XCD'),
			array('name' => 'Saint Martin (French part)', 'currency' => 'Euro', 'currency_code' => 'EUR'),
			array('name' => 'Saint Pierre and Miquelon', 'currency' => 'Euro', 'currency_code' => 'EUR'),
			array('name' => 'Saint Vincent and The Grenadines', 'currency' => 'East Caribbean Dollar', 'currency_code' => 'XCD'),
			array('name' => 'Samoa', 'currency' => 'Tala', 'currency_code' => 'WST'),
			array('name' => 'San Marino', 'currency' => 'Euro', 'currency_code' => 'EUR'),
			array('name' => 'Sao Tome and Principe', 'currency' => 'Dobra', 'currency_code' => 'STD'),
			array('name' => 'Saudi Arabia', 'currency' => 'Saudi Riyal', 'currency_code' => 'SAR'),
			array('name' => 'Senegal', 'currency' => 'CFA Franc BCEAO †', 'currency_code' => 'XOF'),
			array('name' => 'Serbia', 'currency' => 'Serbian Dinar', 'currency_code' => 'RSD'),
			array('name' => 'Seychelles', 'currency' => 'Seychelles Rupee', 'currency_code' => 'SCR'),
			array('name' => 'Sierra Leone', 'currency' => 'Leone', 'currency_code' => 'SLL'),
			array('name' => 'Singapore', 'currency' => 'Singapore Dollar', 'currency_code' => 'SGD'),
			array('name' => 'Sint Maarten (Dutch part)', 'currency' => 'Netherlands Antillean Guilder', 'currency_code' => 'ANG'),
			array('name' => 'Slovakia', 'currency' => 'Euro', 'currency_code' => 'EUR'),
			array('name' => 'Slovenia', 'currency' => 'Euro', 'currency_code' => 'EUR'),
			array('name' => 'Solomon Islands', 'currency' => 'Solomon Islands Dollar', 'currency_code' => 'SBD'),
			array('name' => 'Somalia', 'currency' => 'Somali Shilling', 'currency_code' => 'SOS'),
			array('name' => 'South Africa', 'currency' => 'Rand', 'currency_code' => 'ZAR'),
			array('name' => 'South Georgia and the South Sandwich Islands', 'currency' => 'No universal currency', 'currency_code' => ''),
			array('name' => 'South Sudan', 'currency' => 'South Sudanese Pound', 'currency_code' => 'SSP'),
			array('name' => 'Spain', 'currency' => 'Euro', 'currency_code' => 'EUR'),
			array('name' => 'Sri Lanka', 'currency' => 'Sri Lanka Rupee', 'currency_code' => 'LKR'),
			array('name' => 'Sudan', 'currency' => 'Sudanese Pound', 'currency_code' => 'SDG'),
			array('name' => 'Suri\'name', 'currency' => 'Surinam Dollar', 'currency_code' => 'SRD'),
			array('name' => 'Svalbard and Jan Mayen', 'currency' => 'Norwegian Krone', 'currency_code' => 'NOK'),
			array('name' => 'Swaziland', 'currency' => 'Lilangeni', 'currency_code' => 'SZL'),
			array('name' => 'Sweden', 'currency' => 'Swedish Krona', 'currency_code' => 'SEK'),
			array('name' => 'Switzerland', 'currency' => 'Swiss Franc', 'currency_code' => 'CHF'),
			array('name' => 'Syrian Arab Republic', 'currency' => 'Syrian Pound', 'currency_code' => 'SYP'),
			array('name' => 'Taiwan, Province of China', 'currency' => 'New Taiwan Dollar', 'currency_code' => 'TWD'),
			array('name' => 'Tajikistan', 'currency' => 'Somoni', 'currency_code' => 'TJS'),
			array('name' => 'Tanzania, United Republic of', 'currency' => 'Tanzanian Shilling', 'currency_code' => 'TZS'),
			array('name' => 'Thailand', 'currency' => 'Baht', 'currency_code' => 'THB'),
			array('name' => 'Timor-Leste', 'currency' => 'US Dollar', 'currency_code' => 'USD'),
			array('name' => 'Togo', 'currency' => 'CFA Franc BCEAO †', 'currency_code' => 'XOF'),
			array('name' => 'Tokelau', 'currency' => 'New Zealand Dollar', 'currency_code' => 'NZD'),
			array('name' => 'Tonga', 'currency' => 'Pa\'anga', 'currency_code' => 'TOP'),
			array('name' => 'Trinidad and Tobago', 'currency' => 'Trinidad and Tobago Dollar', 'currency_code' => 'TTD'),
			array('name' => 'Tunisia', 'currency' => 'Tunisian Dinar', 'currency_code' => 'TND'),
			array('name' => 'Turkey', 'currency' => 'New Turkish Lira', 'currency_code' => 'TRY'),
			array('name' => 'Turkmenistan', 'currency' => 'Turkmenistan New Manat', 'currency_code' => 'TMM'),
			array('name' => 'Turks and Caicos Islands', 'currency' => 'US Dollar', 'currency_code' => 'USD'),
			array('name' => 'Tuvalu', 'currency' => 'Australian Dollar', 'currency_code' => 'AUD'),
			array('name' => 'Uganda', 'currency' => 'Uganda Shilling', 'currency_code' => 'UGX'),
			array('name' => 'Ukraine', 'currency' => 'Hryvnia', 'currency_code' => 'UAH'),
			array('name' => 'United Arab Emirates', 'currency' => 'UAE Dirham', 'currency_code' => 'AED'),
			array('name' => 'United Kingdom', 'currency' => 'Pound Sterling', 'currency_code' => 'GBP'),
			array('name' => 'United States', 'currency' => 'US Dollar', 'currency_code' => 'USD'),
			array('name' => 'United States Minor Outlying Islands', 'currency' => 'US Dollar', 'currency_code' => 'USD'),
			array('name' => 'Uruguay', 'currency' => 'Peso Uruguayo', 'currency_code' => 'UYU'),
			array('name' => 'Uzbekistan', 'currency' => 'Uzbekistan Sum', 'currency_code' => 'UZS'),
			array('name' => 'Vanuatu', 'currency' => 'Vatu', 'currency_code' => 'VUV'),
			array('name' => 'Venezuela, Bolivarian Republic of', 'currency' => 'Bolivar', 'currency_code' => 'VEF'),
			array('name' => 'Viet Nam', 'currency' => 'Dong', 'currency_code' => 'VND'),
			array('name' => 'Virgin Islands, British', 'currency' => 'US Dollar', 'currency_code' => 'USD'),
			array('name' => 'Virgin Islands, U.S.', 'currency' => 'US Dollar', 'currency_code' => 'USD'),
			array('name' => 'Wallis And Futuna', 'currency' => 'CFP Franc', 'currency_code' => 'XPF'),
			array('name' => 'Western Sahara', 'currency' => 'Moroccan Dirham', 'currency_code' => 'MAD'),
			array('name' => 'Yemen', 'currency' => 'Yemeni Rial', 'currency_code' => 'YER'),
			array('name' => 'Zambia', 'currency' => 'Kwacha', 'currency_code' => 'ZMK'),
			array('name' => 'Zimbabwe', 'currency' => 'Zimbabwe Dollar', 'currency_code' => 'ZWD'),
		);
		
    	return new ViewModel(array(
                                   'countries' => $countries,
                                   '_metadata' => array('count' => count($countries))
                                   )
                                );
    }
}
