<?php if (count($this->paginator)): ?>
<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($this->paginator as $idx => $item): ?>
    <tr>
      <td><?php echo $item['id'] ?></td>
      <td><?php echo $item['name']; ?></td>
    </tr>
    <?php endforeach ?>
  </tbody>
</table>
<?php endif; ?>

<!-- call pagination control view script  -->
<?php echo $this->paginationControl($this->paginator, 'Elastic', 'pagination', array('route' => 'locations/page')); ?>