<?php if ($this->pageCount): ?>
<?php $query = http_build_query($this->query); ?>
<div class="pagination">
<ul>
  <!-- Previous page link -->
  <?php if (isset($this->previous)): ?>
    <li>
      <a href="<?php echo $this->url($this->route, array('page' => $this->previous, 'type' => $this->type)); ?>?<?php echo $query ?>">&larr; Prev</a>
    </li>
  <?php else: ?>
    <li class="disabled"><a>&larr; Prev</a></li>
  <?php endif; ?>
  
  <!-- Numbered page links -->
  <?php foreach ($this->pagesInRange as $page): ?>
    <?php if ($page != $this->current): ?>
      <li>
        <a href="<?php echo $this->url($this->route, array('page' => $page, 'type' => $this->type)); ?>?<?php echo $query ?>">
          <?php echo $page; ?>
        </a>
      </li>
    <?php else: ?>
      <li class="active"><a><?php echo $page; ?></a></li>
    <?php endif; ?>
  <?php endforeach; ?>
  
  <!-- Next page link -->
  <?php if (isset($this->next)): ?>
    <li>
      <a href="<?php echo $this->url($this->route, array('page' => $this->next, 'type' => $this->type)); ?>?<?php echo $query ?>">Next &rarr;</a>
    </li>
  <?php else: ?>
    <li class="disabled"><a>Next &rarr;</a></li>
  <?php endif; ?>
  </ul>
</div>
<?php endif; ?>